apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger-gateway
  namespace: tsm
  labels:
    team: tsm
    system: mottak
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isAlive
  startup:
    path: /internal/isAlive
    initialDelay: 60
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 1Gi
  secureLogs:
    enabled: false
  kafka:
    pool: nav-dev

